apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ui
  namespace: stock-market-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-ui
  template:
    metadata:
      labels:
        app: app-ui
    spec:
      containers:
        - name: app-ui
          image: docker-app-ui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: app-ui
  namespace: stock-market-dashboard
spec:
  type: LoadBalancer
  ports:
    - port: 3000
  selector:
    app: app-ui
