version: '3.8'

services:
  app-db:
    image: postgres:latest
    container_name: app-postgres
    environment:
      POSTGRES_DB: react-dashboard
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - app-db-data:/var/lib/postgresql

volumes:
  app-db-data: